id: P004180
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG08439
  title: གསོ་བ་རིག་པའི་རང་སྦྱོང་རྒྱུགས་གཞི
  author: ''
  volumes:
    6b4a1e37abd54614ae10a5477809153e:
      image_group_id: I00KG08441
      title: ''
      volume_number: 1
      total_pages: 338
      base_file: v001.txt
